### ISSUE TITLE
OSError. Invalid argument

### ISSUE THREAD

**Issue by pkochubey** [elapouya/python-docx-template#108]
Code works fine into new docker container, but at install it on old Ubuntu 14.04 I catch this issue:
Somebody has any idea?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.4/dist-packages/bottle_sqlalchemy.py", line 155, in wrapper
    rv = callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "./plugins/session.py", line 44, in wrapper
    rv = callback(*args, **kwargs)
  File "./plugins/auth.py", line 33, in wrapper
    return callback(*args, **kwargs)
  File "./plugins/activity.py", line 26, in wrapper
    rv = callback(*args, **kwargs)
  File "./api_routes/cases.py", line 1032, in get_report_pdf
    tpl = DocxTemplate('./template.docx')
  File "/usr/local/lib/python3.4/dist-packages/docxtpl/__init__.py", line 33, in __init__
    self.docx = Document(docx)
  File "/usr/local/lib/python3.4/dist-packages/docx/api.py", line 25, in Document
    document_part = Package.open(docx).main_document_part
  File "/usr/local/lib/python3.4/dist-packages/docx/opc/package.py", line 116, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/usr/local/lib/python3.4/dist-packages/docx/opc/pkgreader.py", line 33, in from_file
    content_types = _ContentTypeMap.from_xml(phys_reader.content_types_xml)
  File "/usr/local/lib/python3.4/dist-packages/docx/opc/phys_pkg.py", line 121, in content_types_xml
    return self.blob_for(CONTENT_TYPES_URI)
  File "/usr/local/lib/python3.4/dist-packages/docx/opc/phys_pkg.py", line 108, in blob_for
    return self._zipf.read(pack_uri.membername)
  File "/usr/lib/python3.4/zipfile.py", line 1117, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.4/zipfile.py", line 1149, in open
    zef_file.seek(zinfo.header_offset, 0)
OSError: [Errno 22] Invalid argument

```

template.docx not corrupted, because I can use unoconv for convert this file to pdf.

**Comment by CircleOnCircles** [comment]
I'm not sure how to reproduce this. Could you provide some more details?

**Comment by pkochubey** [comment]
Let's close this, I don't remember what it is.
