### ISSUE TITLE
<不完整时会报错

### ISSUE THREAD

**Issue by ydhcui** [elapouya/python-docx-template#138]
from docxtpl import DocxTemplate
context = {'value':'sdfdsfsdfsfsf<h1aadcsd</h1>dfsdf'}
doc = DocxTemplate("base.docx")
doc.render(context)

这里 < 没有闭合，然后就报错了
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    doc.render(context)
  File "C:\Python\Python36-32\lib\site-packages\docxtpl\__init__.py", line 151, in render
    tree = self.fix_tables(xml_src)
  File "C:\Python\Python36-32\lib\site-packages\docxtpl\__init__.py", line 166, in fix_tables
    tree = etree.fromstring(xml)
  File "src\lxml\etree.pyx", line 3213, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1067, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src\lxml\parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: error parsing attribute name, line 1, column 1608

**Comment by elapouya** [comment]
Read The Fabulous Manual (Escaping chapter)
