### ISSUE TITLE
ImportError: cannot import name 'DocxTemplate'

### ISSUE THREAD

**Issue by suluoniu** [elapouya/python-docx-template#139]
hello
    i am using windows 10,and "pip install docxtpl",but when i use "from docxtpl import Document"

It display"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\niumzh\Desktop\report\venv\lib\site-packages\docxtpl\__init__.py", line 11, in <module>
    from docx import Document
  File "C:\Users\niumzh\Desktop\report\docx.py", line 1, in <module>
    from docxtpl import DocxTemplate
ImportError: cannot import name 'DocxTemplate'
"
what's the reason

**Comment by elapouya** [comment]
import docxtpl
print docxtpl.__file__
what is the output ?

**Comment by suluoniu** [comment]
>>> import docxtpl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\niumzh\Desktop\report\venv\lib\site-packages\docxtpl\__init__.py", line 11, in <module>
    from docx import Document
  File "C:\Users\niumzh\Desktop\report\docx.py", line 1, in <module>
    from docxtpl import DocxTemplate
ImportError: cannot import name 'DocxTemplate'
>>>
