### ISSUE TITLE
Python Docx 0.8.8

### ISSUE THREAD

**Issue by hugokernel** [elapouya/python-docx-template#174]
Hi,

Since python-docx 0.8.8 (Add support for headers and footers https://github.com/python-openxml/python-docx/blob/master/HISTORY.rst#088-2019-01-07), render with python-docx-template does not work anymore.

Dump (python-docx==0.8.8, docxtpl==0.5.16):
```
Traceback (most recent call last):
  File "lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner              
    response = get_response(request)
  File "lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response          
    response = self.process_exception_by_middleware(e, request)
  File "lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response          
    response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                          
  File "lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view                    
    return self.dispatch(request, *args, **kwargs)
  File "lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch                
    return handler(request, *args, **kwargs)
  File "lib/python2.7/site-packages/django/views/generic/detail.py", line 117, in get                  
    return self.render_to_response(context)
  File "views.py", line 138, in render_to_response                               
    engines[self.engine_name].env)
  File "lib/python2.7/site-packages/docxtpl/__init__.py", line 299, in render                                
    for relKey, xml in headers:
  File "lib/python2.7/site-packages/docxtpl/__init__.py", line 247, in build_headers_footers_xml             
    for relKey, xml in self.get_headers_footers_xml(uri):
  File "lib/python2.7/site-packages/docxtpl/__init__.py", line 238, in get_headers_footers_xml               
    yield relKey, self.xml_to_string(parse_xml(val._target._blob))
  File "lib/python2.7/site-packages/docx/opc/oxml.py", line 37, in parse_xml                                 
    return etree.fromstring(text, oxml_parser)
  File "src/lxml/etree.pyx", line 3230, in lxml.etree.fromstring (src/lxml/etree.c:81070)                                            
  File "src/lxml/parser.pxi", line 1870, in lxml.etree._parseMemoryDocument (src/lxml/etree.c:121231)                                
ValueError: can only parse strings
```

Apparently, there has been a lot of change in the way header and footer are managed and now, val._target._blob value is None in the get_headers_footers_xml

```
    def get_headers_footers_xml(self, uri):
        for relKey, val in self.docx._part._rels.items():
            if val.reltype == uri:
                yield relKey, self.xml_to_string(parse_xml(val._target._blob))
```

**Comment by vc1** [comment]
> Sorry, duplicate of #170
> 
> Do you think you can fix this problem?

@elapouya 

```python
# patch
from docx.opc.oxml import parse_xml
from docx.parts.hdrftr import HeaderPart


def get_headers_footers_xml(self, uri):
    for relKey, val in self.docx._part._rels.items():
        if val.reltype == uri:
            yield relKey, self.xml_to_string(parse_xml(val._target.blob))


def map_headers_footers_xml(self, relKey, xml):
    target = self.docx._part._rels[relKey]._target
    target_new = HeaderPart.load(
        target.partname, target.content_type, xml, target._package)
    target_new._rels = target._rels
    self.docx._part._rels[relKey]._target = target_new


DocxTemplate.get_headers_footers_xml = get_headers_footers_xml
DocxTemplate.map_headers_footers_xml = map_headers_footers_xml
##
```

It's worked  for me  

docxtpl == 0.5.17
docx == 0.8.10

**Comment by elapouya** [comment]
Thank you for your code, I will use it when it will be interesting to use latest python-docx version.
