### ISSUE TITLE
replace_media fails if DocxTemplate is reading and writing to file-like object

### ISSUE THREAD

**Issue by edufresne** [elapouya/python-docx-template#200]
The following code as self.post_processing will try to rename the in-memory file object
```python
import io
file_obj = io.BytesIO(some_content)
file_obj.seek(0)

t = DocxTemplate(file_obj)
t.replace_media('dummy.png', 'other.png')
new_obj = io.BytesIO()
t.render(context)
t.save(new_obj)
```
This throws the error:
```
Traceback (most recent call last):
  File "./header_footer_image_file_obj.py", line 33, in <module>
    tpl.save(file_obj)
  File "C:\Users\EricDufresne\Desktop\python-docx-template\docxtpl\__init__.py", line 543, in save
    self.post_processing(filename)
  File "C:\Users\EricDufresne\Desktop\python-docx-template\docxtpl\__init__.py", line 456, in post_processing
    os.rename(docx_filename,backup_filename)
TypeError: rename: src should be string, bytes or os.PathLike, not _io.BytesIO
```
Simply in the case that a file-like object is being post processed, the temp file must also be in memory using a new BytesIO() object.

**Comment by edufresne** [comment]
I'm going to go ahead and pull request this issue
