### ISSUE TITLE
AttributeError: Possible Bug

### ISSUE THREAD

**Issue by khanfarhan10** [elapouya/python-docx-template#331]
(CertEnv) C:\Users\farha\Documents\GitHub\PythonCertificateGenerator>python DocxGen.py
Traceback (most recent call last):
  File "DocxGen.py", line 5, in <module>
    doc.render(context)
  File "C:\Users\farha\Documents\GitHub\PythonCertificateGenerator\CertEnv\lib\site-packages\docxtpl\__init__.py", line 313, in render
    tree = self.fix_tables(xml_src)
  File "C:\Users\farha\Documents\GitHub\PythonCertificateGenerator\CertEnv\lib\site-packages\docxtpl\__init__.py", line 339, in fix_tables
    columns = tblGrid.findall(ns+'gridCol')
AttributeError: 'NoneType' object has no attribute 'findall'

**Comment by elapouya** [comment]
Please provide python script and docx template so I can reproduce.
