### ISSUE TITLE
OverflowError: int too large to convert to float   using Inline Image.

### ISSUE THREAD

**Issue by XtremeGood** [elapouya/python-docx-template#343]
```
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "c:\python38\lib\threading.py", line 932, in _bootstrap_inner
     self.run()
   File "c:\python38\lib\threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "C:\Users\Dell\OneDrive\Desktop\New Folder\mailer\send_mail.py", line 42, in <lambda>
     target=lambda: self.make_mail_objects(spreadsheet_path)
   File "C:\Users\Dell\OneDrive\Desktop\New Folder\mailer\send_mail.py", line 66, in make_mail_objects
     self.mail_queue.put(self.get_mail_object_from_row(row))
   File "C:\Users\Dell\OneDrive\Desktop\New Folder\mailer\send_mail.py", line 115, in get_mail_object_from_row
     msg.add_message(
   File "C:\Users\Dell\OneDrive\Desktop\New Folder\mailer\prepare_message.py", line 156, in add_message
     template.render(context)
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\docxtpl\__init__.py", line 310, in render
     xml_src = self.build_xml(context, jinja_env)
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\docxtpl\__init__.py", line 269, in build_xml
     xml = self.render_xml(xml, context, jinja_env)
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\docxtpl\__init__.py", line 218, in render_xml
     dst_xml = template.render(context)
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
     self.environment.handle_exception()
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
     reraise(*rewrite_traceback_stack(source=source))
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
     raise value.with_traceback(tb)
   File "<template>", line 1, in top-level template code
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\docxtpl\__init__.py", line 821, in __str__
     return self._insert_image()
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\docxtpl\__init__.py", line 809, in _insert_image
     pic = self.tpl.docx._part.new_pic_inline(
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\docx\parts\story.py", line 57, in new_pic_inline
     cx, cy = image.scaled_dimensions(width, height)
   File "C:\Users\Dell\OneDrive\Desktop\New folder\venv\lib\site-packages\docx\image\image.py", line 158, in scaled_dimensions
     scaling_factor = float(width) / float(self.width)
 OverflowError: int too large to convert to float

```
Image:

![index](https://user-images.githubusercontent.com/40588378/111347196-f8b06380-86a4-11eb-9e9e-c2dfcb714369.jpg)

width:

Mm(5)

**Comment by elapouya** [comment]
Please could you provide a minimal python code and docx template ?

**Comment by XtremeGood** [comment]
Sorry, I forgot when I wrote this. Very strange that I did not share any code. But issue can be closed for now.
