### ISSUE TITLE
For loop works only once

### ISSUE THREAD

**Issue by dadyarri** [elapouya/python-docx-template#352]
Loop iterating over list of dicts, insert only first one item, and breaks the generation (part after loop not inserted)

![image](https://user-images.githubusercontent.com/51821039/115692331-8e57a680-a367-11eb-8b72-e9192e21d427.png)
![image](https://user-images.githubusercontent.com/51821039/115692422-a3ccd080-a367-11eb-95a7-e4ffaea2c526.png)

Using russian, if it's matter

Using this template: [template.docx](https://github.com/elapouya/python-docx-template/files/6357117/template.docx), i got this: [report3.docx](https://github.com/elapouya/python-docx-template/files/6357125/report3.docx)

**Comment by elapouya** [comment]
Please, use a 'p' after the {% :

```
{%p for .. %}
...
{%p endfor %}
```

**Comment by dadyarri** [comment]
@elapouya, thanks for reply, but it didn't work, same result

**Comment by elapouya** [comment]
Could you try the template I modified in attachement
[template.docx](https://github.com/elapouya/python-docx-template/files/6359612/template.docx)

**Comment by dadyarri** [comment]
Got the error:
```python
Traceback (most recent call last):
  File "/home/dadyarri/.tmp/3/fill_report_template.py", line 64, in <module>
    template.render(context)
  File "/home/dadyarri/.local/lib/python3.9/site-packages/docxtpl/__init__.py", line 316, in render
    xml_src = self.build_xml(context, jinja_env)
  File "/home/dadyarri/.local/lib/python3.9/site-packages/docxtpl/__init__.py", line 271, in build_xml
    xml = self.render_xml_part(xml, self.docx._part, context, jinja_env)
  File "/home/dadyarri/.local/lib/python3.9/site-packages/docxtpl/__init__.py", line 226, in render_xml_part
    raise exc
  File "/home/dadyarri/.local/lib/python3.9/site-packages/docxtpl/__init__.py", line 219, in render_xml_part
    template = Template(src_xml)
  File "/home/dadyarri/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1031, in __new__
    return env.from_string(source, template_class=cls)
  File "/home/dadyarri/.local/lib/python3.9/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/dadyarri/.local/lib/python3.9/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/dadyarri/.local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/dadyarri/.local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 34, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'in', got 'for'

```

**Comment by dadyarri** [comment]
here's relevant part of context
![image](https://user-images.githubusercontent.com/51821039/115753858-502ca800-a3a4-11eb-92c5-c1fc19c72398.png)

**Comment by dadyarri** [comment]
same result...

**Comment by elapouya** [comment]
Please, provide python file so I can reproduce your problem.
I do not think it is Cyrillic related, but may be with chapter auto-numbering...

**Comment by dadyarri** [comment]
Gihub does not support uploding py files, so
```python
import pprint
import re
from pathlib import Path

from docxtpl import DocxTemplate, InlineImage
from PIL import Image, ImageDraw, ImageFont


template = DocxTemplate(Path("template.docx"))
source_codes = Path(".").glob("*.py")

context = {
    "number": "3",
    "subject": "qwerty",
    "theme": "asdfgh",
    "author": "qwerty",
    "teacher": "zxcvbn",
    "year": "2021",
    "university": """«Владимирский государственный университет 
имени Александра Григорьевича и Николая Григорьевича Столетовых»
(ВлГУ)""",
    "cathedra": "Кафедра информационных систем и программной инженерии",
    "group": "ИСТ-120",
    "city": "Владимир",
    "tasks": [],
}

for source_code in source_codes:
    if source_code.name != "fill_report_template1.py":
        code = "".join(source_code.open().readlines())
        context["tasks"].append(
            {
                "name": re.search(
                    r"(?<=# Task: ).+",
                    code,
                ).group(0),
                "source": re.search(r"# Task:.+\n*([\s\S]*)", code).group(1),
            }
        )

pprint.pprint(context)

template.render(context)
template.save(Path("report3.docx"))
```

Example of file to include to template:
```python
# Task: <описание задания>

if __name__ == "__main__":
    pass

```

**Comment by dadyarri** [comment]
> may be with chapter auto-numbering...
Checked this, nope, doesn't work

**Comment by dadyarri** [comment]
Don't know why, but if i remove angle brackets (`<` `>`) from `task.name` it's fixing.

**Comment by elapouya** [comment]
Could you try : 

`template.render(context, autoescape=True)`

**Comment by dadyarri** [comment]
Working, thanks!
