### ISSUE TITLE
AttributeError: 'InlineImage' object has no attribute 'current_rendering_part'

### ISSUE THREAD

**Issue by rishi1804** [elapouya/python-docx-template#413]
Please explain something about this error. I am getting this when I try to render my JSON. There are multiple InlineImage objects in that JSON.

**Comment by WilliamWCYoung** [comment]
I am also getting a similar issue!

**Comment by elapouya** [comment]
please provide a fully runnig test case

**Comment by rishi1804** [comment]
@WilliamWCYoung I solved the issue in my case. If you share the way you are using it, maybe I would be able to help.

**Comment by WilliamWCYoung** [comment]
I also solved my own case - it was after bumping. For the use case I have I have a custom class which assumes certain behaviour. Thanks for a great project!

**Comment by joshuadavidthomas** [comment]
@rishi1804 @WilliamWCYoung Mind sharing how you fixed your issue? I'm running into the same area and am down the rabbit hole trying to debug what's going wrong. Could really use a nudge in the right direction.

**Comment by WilliamWCYoung** [comment]
So the solution I had was very specific to the changes I made on-top of the package (I had assumed behaviour of private internal variables). If you have similar custom logic, I would suggest that you add debugging and check that the variables are there and populated as you expect, if not you'll maybe need to call extra methods. For instance, and I'm not by my code now, there was an init method that was now being called through the normal flow that I was not being called in my use case.

**Comment by dalonsoma** [comment]
Could you tell us what you changed in the code? I have the same problem but right now it is difficult for me to access the code of library

**Comment by elapouya** [comment]
please provide a fully runnig test case

**Comment by civilengradil** [comment]
You must declare DocxTemplate prior to creating InLineImage e.g., 
# first creating tpl instance here
 **tpl** = DocxTemplate(f'C:\\Python\\template\\{templateFileName}.docx')
#later the JSON entry
{
            'image': InlineImage(**tpl**, imageFilePath, height=Inches(3.4), width=Inches(3.4*img.width/img.height)),
            'label': f'PHOTO {phtoNameLetter}\\n {item.properties["Photo_Caption"]}',
            })

**Comment by SergeyZaykov** [comment]
@elapouya 
> please provide a fully runnig test case

You are welcome. It is [a patch against tests/inline_image.py ](https://github.com/user-attachments/files/18680367/test_case.patch). It lets you reproduce the error.

My output:
` python inline_image_bad.py
Traceback (most recent call last):
  File "/home/my/test/docxtpl/inline_image_bad.py", line 50, in <module>
    tpl.render(context, jinja_env)
  File "/usr/local/lib/python3.11/site-packages/docxtpl/template.py", line 368, in render
    xml_src = self.build_xml(context, jinja_env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/docxtpl/template.py", line 315, in build_xml
    xml = self.render_xml_part(xml, self.docx._part, context, jinja_env)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/docxtpl/template.py", line 239, in render_xml_part
    dst_xml = template.render(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 5, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/docxtpl/inline_image.py", line 39, in __html__
    return self._insert_image()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/docxtpl/inline_image.py", line 24, in _insert_image
    pic = self.tpl.current_rendering_part.new_pic_inline(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'current_rendering_part'
`



The cause of the error is that the DocxTemplate variable has a null value.

It is obviously a stupid mistake, but using your own class can make this mistake easily.

This error is not yours; this error is package users. @WilliamWCYoung use his own class and I use my own class and got the error.

My suggestion is to add to docxtpl/inline_image.py these lines:
    def __init__(self, tpl, image_descriptor, width=None, height=None):
        if tpl is None:
           raise Exception("The document template is None. Create the document template first.")

**Comment by SergeyZaykov** [comment]
> Please explain something about this error. I am getting this when I try to render my JSON. There are multiple InlineImage objects in that JSON.

@dalonsoma Do you use your own class?

**Comment by SergeyZaykov** [comment]
I checked my program: yes, my own class sets None value for the DocxTemplate variable

**Comment by SergeyZaykov** [comment]
I'm so sorry.
docxtpl                       0.16.6
