### ISSUE TITLE
is it possible to use unicode string in template variable?

### ISSUE THREAD

**Issue by trivita** [elapouya/python-docx-template#70]
like {{ åß∂ƒ }} for an instance

**Comment by elapouya** [comment]
you tried ?

2017-02-15 16:50 GMT+01:00 trivita <notifications@github.com>:

**Comment by trivita** [comment]
this is what i got 

`Traceback (most recent call last):
  File "/Users/trivita/mydev/send2grouk/testtpl.py", line 100, in <module>
    main()
  File "/Users/trivita/mydev/send2grouk/testtpl.py", line 90, in main
    doc.render(context)
  File "/usr/local/lib/python2.7/site-packages/docxtpl/__init__.py", line 126, in render
    xml_src = self.build_xml(context,jinja_env)
  File "/usr/local/lib/python2.7/site-packages/docxtpl/__init__.py", line 91, in build_xml
    xml = self.render_xml(xml, context, jinja_env)
  File "/usr/local/lib/python2.7/site-packages/docxtpl/__init__.py", line 83, in render_xml
    template = Template(src_xml)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 926, in __new__
    return env.from_string(source, template_class=cls)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char u'\xe5' at 4067`

**Comment by trivita** [comment]
looks like jinja2 doesnt support that

**Comment by trivita** [comment]
so python3 support this
