### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by jesternotfromleicester** [elapouya/python-docx-template#72]
Hi guys,

thank you for the great work. I have an issue with the compiling of all examples listed. I have installed docxtpl with pip. While running the first example i get following errors:

[root@localhost ~]# python template2.py
Traceback (most recent call last):
  File "template2.py", line 24, in <module>
    tpl.render(context)
  File "/usr/lib/python2.6/site-packages/docxtpl/__init__.py", line 126, in rend
    xml_src = self.build_xml(context,jinja_env)
  File "/usr/lib/python2.6/site-packages/docxtpl/__init__.py", line 90, in build
    xml = self.patch_xml(xml)
  File "/usr/lib/python2.6/site-packages/docxtpl/__init__.py", line 45, in patch
    src_xml = re.sub(r'(?<={)(<[^>]*>)+(?=[\{%])|(?<=[%\}])(<[^>]*>)+(?=\})','',
TypeError: sub() got an unexpected keyword argument 'flags'

All help would be greatly appreciated.

**Comment by elapouya** [comment]
Please use python 2.7
